from __future__ import annotations

from pathlib import Path

CODEX_RULES_START = "<!-- project-copilot:codex-rules:start -->"
CODEX_RULES_END = "<!-- project-copilot:codex-rules:end -->"


def ensure_codex_native_files(root: Path) -> list[Path]:
    docs_dir = root / "docs"
    docs_dir.mkdir(exist_ok=True)

    files = {
        docs_dir / "CODEX_WORKFLOW.md": render_codex_workflow_doc(),
    }
    written: list[Path] = []
    agents = root / "AGENTS.md"
    _write_text(agents, merge_agents_md(agents.read_text(encoding="utf-8") if agents.exists() else ""))
    written.append(agents)
    for path, content in files.items():
        _write_text(path, content)
        written.append(path)
    return written


def merge_agents_md(existing: str) -> str:
    rules = _managed_agents_block()
    if CODEX_RULES_START in existing and CODEX_RULES_END in existing:
        start = existing.index(CODEX_RULES_START)
        end = existing.index(CODEX_RULES_END) + len(CODEX_RULES_END)
        return existing[:start].rstrip() + "\n\n" + rules + "\n" + existing[end:].lstrip()
    if not existing.strip():
        return rules + "\n"
    return existing.rstrip() + "\n\n" + rules + "\n"


def render_agents_md() -> str:
    return "\n".join(
        [
            "# Agents",
            "",
            "你的首要职责不是写代码。",
            "",
            "你的首要职责是：",
            "",
            "确保项目持续朝着既定目标演进。",
            "",
            "如果开发行为与项目目标冲突：",
            "",
            "必须优先阻止偏离，而不是继续实现功能。",
            "",
            "你是 Codex。",
            "你负责开发。",
            "同时你必须维护 `.ai` 分层项目记忆，避免把维护动作写进事实层。",
            "",
            "## 项目使命优先级",
            "",
            "在任何开发行为之前必须检查：",
            "",
            "1. `PROJECT_CONTEXT.md`",
            "2. 当前请求是否符合项目使命",
            "3. 当前请求是否符合目标用户",
            "4. 当前请求是否符合 MVP",
            "",
            "如果任一项不符合，必须暂停执行并提醒用户确认。",
            "",
            "## 每次开始开发前",
            "",
            "- 阅读 `.ai/PROJECT_CONTEXT.md`",
            "- 阅读 `.ai/STATUS.md`",
            "- 阅读 `.ai/ROADMAP.md`",
            "- 阅读 `.ai/DECISIONS.md`",
            "",
            "## 每次完成开发后",
            "",
            "- 更新 `.ai/STATUS.md`",
            "- 追加 `.ai/WORKLOG.md`",
            "- 当触发决策条件时，追加 `.ai/DECISIONS.md`",
            "- 当出现长期事实、重要事件、关键里程碑或不应遗忘的信息时，更新 `.ai/MEMORY.md`",
            "- 维护型动作不要写进 `.ai/MEMORY.md`；同步、复盘和整理只应留下真实事件摘要",
            "- 当出现未确认判断、待验证分析或低置信度结论时，更新 `.ai/HYPOTHESES.md`",
            "- 当触发认知沉淀条件时，更新 `.ai/KNOWLEDGE.md`",
            "- 当发生状态变化、重要事件、决策变化或里程碑时，更新 `.ai/history/YYYY-MM.md`",
            "- 当项目创建时间、运行天数、决策数量、里程碑数量、健康度或偏航指数变化时，更新 `.ai/metrics.md`",
            "",
            "## 项目守护机制",
            "",
            "### 超出 MVP",
            "",
            "当用户请求超出 `.ai/PROJECT_CONTEXT.md` 的 MVP 范围时，必须：",
            "",
            "- 明确指出该请求超出 MVP。",
            "- 停止实现该功能。",
            "- 要求用户选择：",
            "  1. 纳入当前版本",
            "  2. 延后到未来版本",
            "  3. 取消该需求",
            "",
            "在用户选择之前，禁止直接实现。",
            "",
            "### 偏离目标用户",
            "",
            "当用户请求与 `.ai/PROJECT_CONTEXT.md` 的目标用户不匹配时，必须提醒：",
            "",
            "- 当前目标用户是谁。",
            "- 当前需求是否匹配该用户。",
            "- 继续前需要用户确认。",
            "",
            "### 与历史决策冲突",
            "",
            "当用户请求与 `.ai/DECISIONS.md` 冲突时，必须：",
            "",
            "- 引用 `.ai/DECISIONS.md` 中的相关决策。",
            "- 明确说明冲突点。",
            "- 请求用户确认是否推翻旧决策。",
            "",
            "禁止自动覆盖旧决策。",
            "",
            "## DECISIONS.md 强制写入规则",
            "",
            "发生以下情况时，必须追加写入 `.ai/DECISIONS.md`：",
            "",
            "- 技术栈变化",
            "- 架构变化",
            "- MVP 范围变化",
            "- 放弃已有功能",
            "- 引入重大依赖",
            "- 部署方式变化",
            "",
            "写入格式必须统一：",
            "",
            "```text",
            "日期：",
            "",
            "决策：",
            "",
            "原因：",
            "",
            "影响：",
            "```",
            "",
            "## KNOWLEDGE.md 写入规则",
            "",
            "只有以下情况允许写入 `.ai/KNOWLEDGE.md`：",
            "",
            "- 新的最佳实践",
            "- 重要设计经验",
            "- 开源项目启发",
            "- 用户反馈总结",
            "- 产品认知提升",
            "",
            "禁止写入：",
            "",
            "- 代码实现细节",
            "- 临时调试经验",
            "",
            "`KNOWLEDGE.md` 用于认知沉淀，不用于技术日志。",
            "",
            "## HYPOTHESES.md 写入规则",
            "",
            "只有以下情况允许写入 `.ai/HYPOTHESES.md`：",
            "",
            "- 未确认判断",
            "- 待验证分析",
            "- 低置信度结论",
            "- 需要用户确认的推测",
            "",
            "禁止写入：",
            "",
            "- 已确认事实",
            "- 已确认决策",
            "- 日常工作日志",
            "",
            "HYPOTHESES.md 用于保存未确认内容，不用于事实归档。",
            "",
            "## WORKLOG.md 强制追加规则",
            "",
            "每次开发完成后必须按时间顺序追加 `.ai/WORKLOG.md`，禁止覆盖历史内容。",
            "",
            "每条记录必须包含：",
            "",
            "- 日期",
            "- 完成内容",
            "- 遇到问题",
            "- 明日计划",
            "",
            "## 项目复盘触发机制",
            "",
            "- 当 `.ai/WORKLOG.md` 连续 7 天未更新时，必须提醒用户：建议进行项目复盘。",
            "- 当项目连续 30 天未复盘时，必须建议生成项目周报或月报。",
            "",
            "## 不可违反的规则",
            "",
            "- 不要覆盖历史决策。",
            "- 不要把临时状态写进 `PROJECT_CONTEXT.md`。",
            "- 不要未经用户确认扩大 MVP 范围。",
            "- 不要使用模糊触发词作为执行条件。",
            "- 每条守护提醒必须包含明确触发条件、判断标准和执行动作。",
            "",
            "## 用户表达",
            "",
            "- `commit` = 保存进度",
            "- `push` = 备份到云端",
            "- `release` = 发布版本",
            "- `tag` = 版本标记",
            "",
        ]
    )


def _managed_agents_block() -> str:
    return "\n".join([CODEX_RULES_START, render_agents_md().strip(), CODEX_RULES_END])


def _write_text(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")


def render_codex_workflow_doc() -> str:
    return "\n".join(
        [
            "# Project Copilot 与 Codex",
            "",
            "Project Copilot 为 Codex 安装分层项目记忆。",
            "",
            "Codex 负责开发。",
            "",
            "Project Copilot 负责记录项目历史、决策和演进过程。",
            "",
            "一句话：",
            "",
            "Git 记录代码历史。",
            "",
            "Project Copilot 记录项目历史。",
            "",
            "## 为什么需要 Project Copilot",
            "",
            "随着项目持续开发，人们经常忘记：",
            "",
            "- 为什么开始这个项目",
            "- 为什么这样设计",
            "- 为什么放弃某些需求",
            "- 项目如何演化到今天",
            "",
            "Git 能告诉你：",
            "",
            "改了什么。",
            "",
            "Project Copilot 能告诉你：",
            "",
            "为什么改。",
            "",
            "目标是让项目在一年后仍然能够回答：",
            "",
            "- 为什么存在",
            "- 为什么这样设计",
            "- 为什么放弃某些功能",
            "- 如何一步步发展到今天",
            "",
            "## 第一次使用",
            "",
            "接管已有项目：",
            "",
            "```bash",
            "project-copilot adopt",
            "```",
            "",
            "或者初始化新项目：",
            "",
            "```bash",
            "project-copilot init",
            "```",
            "",
            "先贴完整项目方案，Project Copilot 会先提取项目使命、目标用户、商业目标、MVP 范围、技术栈、当前阶段、初始 Roadmap 和初始 Decisions，缺失时再追问。",
            "",
            "系统将生成：",
            "",
            "- `.ai/`",
            "- `AGENTS.md`",
            "- 项目记忆规则",
            "",
            "## 推荐工作流",
            "",
            "### 每天开始",
            "",
            "在项目目录打开：",
            "",
            "```bash",
            "codex",
            "```",
            "",
            "推荐输入：",
            "",
            "```text",
            "继续开发这个项目",
            "```",
            "",
            "### 开发过程中",
            "",
            "正常与 Codex 对话即可。",
            "",
            "Project Copilot 会通过分层项目记忆帮助 Codex 理解：",
            "",
            "- 项目目标",
            "- MVP 范围",
            "- 历史决策",
            "- 项目状态",
            "",
            "### 每天结束",
            "",
            "推荐输入：",
            "",
            "```text",
            "今天结束工作",
            "```",
            "",
            "帮助更新：",
            "",
            "- 项目状态",
            "- 工作日志",
            "- 分层记忆",
            "",
            "### 每周复盘",
            "",
            "推荐输入：",
            "",
            "```text",
            "复盘项目",
            "```",
            "",
            "查看：",
            "",
            "- 本周完成",
            "- 关键决策",
            "- 风险变化",
            "- 路线图推进情况",
            "",
            "### 项目变复杂时",
            "",
            "推荐输入：",
            "",
            "```text",
            "项目偏航检查",
            "```",
            "",
            "确认：",
            "",
            "- 是否偏离目标用户",
            "- 是否超出 MVP",
            "- 是否与历史决策冲突",
            "",
            "## 项目记忆结构",
            "",
            "`PROJECT_CONTEXT.md`",
            "",
            "记录项目使命和目标用户。",
            "",
            "`STATUS.md`",
            "",
            "记录当前状态。",
            "",
            "`ROADMAP.md`",
            "",
            "记录项目计划。",
            "",
            "`MEMORY.md`",
            "",
            "记录稳定事实、重要事件、关键里程碑和不应遗忘的信息。",
            "",
            "`HYPOTHESES.md`",
            "",
            "记录未确认判断、待验证分析和低置信度结论。",
            "",
            "`DECISIONS.md`",
            "",
            "记录重要决策及原因。",
            "",
            "`WORKLOG.md`",
            "",
            "记录每日工作，只写实际完成内容，不写推测或规划。",
            "",
            "`KNOWLEDGE.md`",
            "",
            "记录学习和经验沉淀。",
            "",
            "## 最佳实践",
            "",
            "建议：",
            "",
            "- 每天结束时更新项目状态",
            "- 每周进行一次项目复盘",
            "- 重要决策及时记录",
            "- MVP 变更前先确认影响",
            "",
            "## 项目秘书理念",
            "",
            "Project Copilot 不负责写代码。",
            "",
            "Project Copilot 负责：",
            "",
            "- 记录",
            "- 提醒",
            "- 归档",
            "- 复盘",
            "- 守护项目方向",
            "",
            "Codex 负责把事情做出来。",
            "",
            "Project Copilot 负责记住为什么这样做。",
            "",
        ]
    )
